version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: taskman
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d